/* Modification table */
CREATE TABLE ADDITIONAL_OPTIONS (
    ID_ORDER    INTEGER,
    ID_OPTIONS  INTEGER
);
CREATE TABLE "CAR_DEFAULT-OPTIONS" (
    ID_OPTIONS    INTEGER,
    ID_EQUIPMENT  INTEGER
);
CREATE TABLE CAR_MODIFICATION (
    ID             INTEGER NOT NULL,
    ID_CAR_MODEL   INTEGER,
    CAR_BODY_TYPE  INTEGER,
    ENGINE_TYPE    INTEGER,
    DRIVE_GEAR     INTEGER,
    GEAR_BOX       INTEGER
);
CREATE TABLE DRIVE_GEAR (
    ID    INTEGER NOT NULL,
    NAME  CHAR(10)
);
CREATE TABLE ENGINE_TYPE (
    ID    INTEGER NOT NULL,
    NAME  CHAR(10)
);
CREATE TABLE GEAR_BOX (
    ID    INTEGER NOT NULL,
    NAME  CHAR(10)
);

DROP TABLE CONFIGURATION;
ALTER TABLE CAR DROP ID_CAR_MODELS;
ALTER TABLE CAR ALTER ID_MODELS TO ID_MODIFICATION;

/***********************PRIMARY KEY***********************/
/*ALTER TABLE CAR_BODY_TYPE ADD CONSTRAINT PK_CAR_BODY_TYPE PRIMARY KEY (ID);*/
/*ALTER TABLE CAR_MODELS ADD CONSTRAINT PK_CAR_MODELS PRIMARY KEY (ID);*/
ALTER TABLE CAR_MODIFICATION ADD CONSTRAINT PK_CAR_MODIFICATION PRIMARY KEY (ID);
ALTER TABLE DRIVE_GEAR ADD CONSTRAINT PK_DRIVE_GEAR PRIMARY KEY (ID);
ALTER TABLE ENGINE_TYPE ADD CONSTRAINT PK_ENGINE_TYPE PRIMARY KEY (ID);
ALTER TABLE GEAR_BOX ADD CONSTRAINT PK_GEAR_BOX PRIMARY KEY (ID);
/*ALTER TABLE OPTIONS ADD CONSTRAINT PK_OPTIONS PRIMARY KEY (ID);*/

/***********************FOREIGN KEY***********************/
ALTER TABLE ADDITIONAL_OPTIONS ADD CONSTRAINT FK_ADDITIONAL_OPTIONS_1 FOREIGN KEY (ID_OPTIONS) REFERENCES OPTIONS (ID);
ALTER TABLE ADDITIONAL_OPTIONS ADD CONSTRAINT FK_ADDITIONAL_OPTIONS_2 FOREIGN KEY (ID_ORDER) REFERENCES "ORDER" (ID);
ALTER TABLE CAR ADD CONSTRAINT FK_CAR_2 FOREIGN KEY (ID_MODIFICATION) REFERENCES CAR_MODIFICATION (ID);
ALTER TABLE "CAR_DEFAULT-OPTIONS" ADD CONSTRAINT "FK_CAR_DEFAULT-OPTIONS_1" FOREIGN KEY (ID_OPTIONS) REFERENCES OPTIONS (ID);
ALTER TABLE "CAR_DEFAULT-OPTIONS" ADD CONSTRAINT "FK_CAR_DEFAULT-OPTIONS_2" FOREIGN KEY (ID_EQUIPMENT) REFERENCES CAR_EQUIPMENT (ID);
ALTER TABLE CAR_MODIFICATION ADD CONSTRAINT FK_CAR_MODIFICATION_1 FOREIGN KEY (ID_CAR_MODEL) REFERENCES CAR_MODELS (ID);
ALTER TABLE CAR_MODIFICATION ADD CONSTRAINT FK_CAR_MODIFICATION_2 FOREIGN KEY (ENGINE_TYPE) REFERENCES ENGINE_TYPE (ID);
ALTER TABLE CAR_MODIFICATION ADD CONSTRAINT FK_CAR_MODIFICATION_3 FOREIGN KEY (DRIVE_GEAR) REFERENCES DRIVE_GEAR (ID);
ALTER TABLE CAR_MODIFICATION ADD CONSTRAINT FK_CAR_MODIFICATION_4 FOREIGN KEY (GEAR_BOX) REFERENCES GEAR_BOX (ID);
ALTER TABLE CAR_MODIFICATION ADD CONSTRAINT FK_CAR_MODIFICATION_5 FOREIGN KEY (CAR_BODY_TYPE) REFERENCES CAR_BODY_TYPE (ID);


